[package]
name = "orderbook-ws"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "^1.0.203", features = ["derive"]}
serde_json ={ version = "^1.0.120"}
rand = "0.8"

